---
title: "referendum2018"
author: "Gabriel Preda"
date: "October 6, 2018"
output: html_document
---



```{r setup, include=FALSE}
library(jsonlite)
library(rgdal)
library(tidyr)
library(leaflet)
require(plotrix)
library(plotly)
library(plyr)
library(dplyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(gtools)
options(knitr.table.format = "html") 
```


```{r read_presence}
PATH1="../../Kaggle/input/elementary-school-admission-romania-2014/"
PATH2="../../Kaggle/input/referendum-ro-2018/"

```



```{r geojson_data}
#geoJSON used for rendering, has lower number of points
rgeojson <- readOGR(paste(PATH1,"romania.geojson",sep=""))#, layer="OGRGeoJSON")
#geoJSON used for retrieving population information from census
geojson <- readLines(paste(PATH1,"ro_judete_poligon.geojson",sep=""), warn = FALSE, encoding = "UTF-8") %>%
  paste(collapse = "\n") %>%
  fromJSON(simplifyVector = FALSE)
```


```{r census_population}
# Gather population for all counties ('judet')
poplist <- lapply(geojson$features, function(feat) {
  c(as.character(feat$properties$name),as.integer(feat$properties$pop1948),as.integer(feat$properties$pop1956),as.integer(feat$properties$pop1977), as.integer(feat$properties$pop1992), as.integer(feat$properties$pop2002),as.integer(feat$properties$pop2011))

})
census.years<-c("1948", "1956","1977", "1992", "2001", "2011")
pop <- matrix(unlist(poplist), nrow = 42, ncol = 7, byrow = TRUE)
colnames(pop) <- c("judet",census.years)
population2011 <- pop[,c(1,7)]
``` 

```{r rbubbly}
rbubbly <- function(dataset, x_column, y_column, bubble_column, color_column,
                    slider_column, text_column,
                    x_title=NA, y_title=NA, title=NA,
                    x_is_log=TRUE, y_is_log=FALSE,scale_bubble=1) {

  library(plotly)

  if(x_is_log)
    xtype="log"
  else
    xtype=NA

  if(y_is_log)
    ytype="log"
  else
    ytype=NA

  xmin = min(x_column)
  xmax = max(x_column)
  ymin = min(y_column)
  ymax = max(y_column)
  print(xmin)
  print(xmax)
  print(ymin)
  print(ymax)
  smin = scale_bubble * sqrt(xmin*ymin)
  smax = scale_bubble * sqrt(xmax*ymax)
  p <-
    plot_ly(data = dataset,
      x = x_column,
      y = y_column,
      size = bubble_column,
      color = color_column,
      frame = slider_column,
      text = text_column,
      hoverinfo = "Country: ~text",
      type = 'scatter',
      mode = 'markers',
      marker = list(opacity = 0.5),
      sizes = c(smin, smax)
    ) %>%
    layout(
      title = title,
      xaxis = list(
        title = x_title,
        type = xtype
      ),
      yaxis = list(
        title = y_title,
        type = ytype
      )
    )
  return (p)
}

```

```{r read_referendum_data}
presence_0610 <- read.csv(paste(PATH2,"presence_RO_2018-10-06_10-00.csv",sep=""))
presence_0613 <- read.csv(paste(PATH2,"presence_RO_2018-10-06_13-00.csv",sep=""))
presence_0616 <- read.csv(paste(PATH2,"presence_RO_2018-10-06_16-00.csv",sep=""))
presence_0619 <- read.csv(paste(PATH2,"presence_RO_2018-10-06_19-00.csv",sep=""))
presence_0621 <- read.csv(paste(PATH2,"presence_RO_2018-10-06_21-00.csv",sep=""))
presence_0710 <- read.csv(paste(PATH2,"presence_RO_2018-10-07_10-00.csv",sep=""))
presence_0713 <- read.csv(paste(PATH2,"presence_RO_2018-10-07_13-00.csv",sep=""))


presence_0610$date = as.POSIXct("2018-10-06T10:00:00.000", format="%Y-%m-%dT%H:%M")
presence_0613$date = as.POSIXct("2018-10-06T13:00:00.000", format="%Y-%m-%dT%H:%M")
presence_0616$date = as.POSIXct("2018-10-06T16:00:00.000", format="%Y-%m-%dT%H:%M")
presence_0619$date = as.POSIXct("2018-10-06T19:00:00.000", format="%Y-%m-%dT%H:%M")
presence_0621$date = as.POSIXct("2018-10-06T21:00:00.000", format="%Y-%m-%dT%H:%M")
presence_0710$date = as.POSIXct("2018-10-07T10:00:00.000", format="%Y-%m-%dT%H:%M")
presence_0713$date = as.POSIXct("2018-10-07T13:00:00.000", format="%Y-%m-%dT%H:%M")


presence_0610$crt = 6.10
presence_0613$crt = 6.13
presence_0616$crt = 6.16
presence_0619$crt = 6.19
presence_0621$crt = 6.21
presence_0710$crt = 7.10
presence_0713$crt = 7.13


```

```{r smart_bind}
presence = smartbind(presence_0610, presence_0613, presence_0616, presence_0619, presence_0621, presence_0710, presence_0713)

colnames(presence) <- c("County", "Municipality", "City", "SIRUTA", "Circumscription", "Location", "Medium", "Electors", "Votes.Registered", "Votes.not.Registered", "Votes.Mobile", "Votes.Total", "Date.Hour", "Time")
```


```{r rbubbly_prepare}

presence %>% group_by(Time, County, Medium) %>% 
  summarise(Registered.Percent = 100* sum(Votes.Registered)/sum(Electors),
  Not.Registered.Percent = 100 * sum(Votes.not.Registered)/sum(Electors),
  Mobile.Percent = 100 * sum(Votes.Mobile) / sum(Electors),
  Total.Percent = 100 * sum(Votes.Total)/sum(Electors),
  Total.Electors = sum(Electors)) %>% ungroup() -> presence_grouped
```

```{r rbubbly_show}
rbubbly(presence_grouped,
        x_column = presence_grouped$Registered.Percent, y_column = presence_grouped$Total.Percent,
        bubble_column = presence_grouped$Total.Electors, color_column = presence_grouped$Medium,
        slider_column = presence_grouped$Time, text_column = presence_grouped$County,
        x_title="Percent of registered votes from registered electors", y_title="Percent of total votes from registered electors",                    title="Referendum 2018 Romania\nPercent of votes per county, grouped by Rural/Urban medium",
        x_is_log=FALSE, y_is_log=FALSE,scale_bubble=100)
```
